apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: magento
spec:
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
          env:
            - name: discovery.type
              value: single-node
          ports:
            - containerPort: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: magento
spec:
  ports:
    - port: 9200
  selector:
    app: elasticsearch
