apiVersion: v1
kind: Secret

metadata:
  name: jenkins-secret
  namespace: devops

type: Opaque

stringData:
  # Admin local de emergência
  JENKINS_ADMIN_ID: admin
  JENKINS_ADMIN_PASSWORD: admin123

  # Keycloak
  KEYCLOAK_CLIENT_ID: jenkins-dev
  KEYCLOAK_CLIENT_SECRET: admin123